# Generated by Django 3.1.1 on 2021-05-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='sl',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='tp',
        ),
    ]
