# Generated by Django 3.1.1 on 2021-05-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_auto_20210510_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
