# Generated by Django 3.1.1 on 2021-05-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0003_deal_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='order',
            field=models.IntegerField(),
        ),
    ]
