# Generated by Django 3.0.8 on 2020-11-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('abs_correlation', models.FloatField()),
                ('n', models.PositiveSmallIntegerField()),
                ('history_size', models.PositiveSmallIntegerField()),
                ('min_similar', models.PositiveSmallIntegerField()),
                ('stop', models.FloatField()),
                ('take', models.FloatField()),
                ('mean', models.FloatField()),
                ('sd', models.FloatField()),
            ],
            options={
                'db_table': 'first_settings',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Currency')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Setting')),
            ],
            options={
                'db_table': 'first_strategies',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy', models.BooleanField()),
                ('n_max', models.PositiveSmallIntegerField()),
                ('forecast', models.FloatField()),
                ('result', models.FloatField(default=0)),
                ('status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='history.OrderStatus')),
                ('time_marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.TimeMarker')),
            ],
            options={
                'db_table': 'first_results',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Result')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Strategy')),
                ('time_marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.TimeMarker')),
            ],
            options={
                'db_table': 'first_orders',
                'unique_together': {('strategy', 'time_marker')},
            },
        ),
    ]
