# Generated by Django 3.0.8 on 2020-08-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('abs_correlation', models.FloatField()),
                ('n', models.PositiveSmallIntegerField()),
                ('history_size', models.PositiveSmallIntegerField()),
                ('min_similar', models.PositiveSmallIntegerField()),
                ('stop', models.FloatField()),
                ('take', models.FloatField()),
                ('mean', models.FloatField()),
                ('sd', models.FloatField()),
            ],
            options={
                'db_table': 'first_settings',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Currency')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Setting')),
            ],
            options={
                'db_table': 'first_strategies',
            },
        ),
    ]
