# Generated by Django 3.0.8 on 2020-11-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20201108_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='n_max',
            new_name='n',
        ),
    ]
