# Generated by Django 3.0.8 on 2020-08-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='strategy',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='first.Strategy'),
            preserve_default=False,
        ),
    ]
