# Generated by Django 3.0.8 on 2020-08-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_order_strategy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='first_orders',
        ),
    ]
