# Generated by Django 3.0.8 on 2020-11-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20201128_1223'),
        ('first', '0003_auto_20201108_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['time_marker']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['time_marker']},
        ),
        migrations.RenameField(
            model_name='result',
            old_name='result',
            new_name='profit',
        ),
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='history.OrderStatus'),
        ),
    ]
