# Generated by Django 3.0.8 on 2020-08-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20200830_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='close_marker',
            new_name='close_n',
        ),
    ]
