# Generated by Django 3.0.8 on 2020-08-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20200830_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='result',
            new_name='forecast',
        ),
    ]
