# Generated by Django 3.1.1 on 2021-02-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_result_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.order'),
        ),
    ]
