# Generated by Django 3.0.8 on 2020-08-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20200830_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_result',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='result',
            field=models.FloatField(default=None, null=True),
        ),
    ]
