# Generated by Django 3.0.8 on 2020-09-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('first', '0007_auto_20200830_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderSettings',
        ),
        migrations.AlterModelTable(
            name='ordersettings',
            table='first_order',
        ),
    ]
