# Generated by Django 3.0.8 on 2020-09-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20200930_1531'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordersettings',
            table='first_order_settings',
        ),
    ]
