# Generated by Django 3.1.1 on 2021-03-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20210227_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='history',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='mean',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='sd',
            field=models.FloatField(default=0),
        ),
    ]
