# Generated by Django 3.1.1 on 2021-03-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_auto_20210318_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='history',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='mean',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='sd',
            field=models.FloatField(),
        ),
    ]
