# Generated by Django 3.0.8 on 2020-09-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('first', '0009_auto_20200930_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderSettings',
            new_name='OrderSetting',
        ),
    ]
