# Generated by Django 3.0.8 on 2020-09-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('first', '0010_auto_20200930_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersetting',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='ordersetting',
            name='time_marker',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.OrderSetting')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Strategy')),
                ('time_marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.TimeMarker')),
            ],
            options={
                'db_table': 'first_orders',
            },
        ),
    ]
