# Generated by Django 3.1.1 on 2021-03-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_remove_result_mean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='mean',
            new_name='mean_min',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='sd',
            new_name='sd_min',
        ),
    ]
