# Generated by Django 3.0.8 on 2020-09-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_auto_20200930_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_setting',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='first.OrderSetting'),
        ),
    ]
