# Generated by Django 3.1.1 on 2021-03-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_auto_20210328_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='mean_max',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='setting',
            name='n_min',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='setting',
            name='sd_max',
            field=models.FloatField(default=1.5),
        ),
    ]
