# Generated by Django 3.1.1 on 2021-03-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_auto_20210328_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='mean_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='n_min',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sd_max',
            field=models.FloatField(),
        ),
    ]
