# Generated by Django 3.0.8 on 2020-10-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_close',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
