# Generated by Django 3.1.1 on 2021-03-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_auto_20210328_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='history',
        ),
        migrations.AddField(
            model_name='order',
            name='history',
            field=models.IntegerField(default=1),
        ),
    ]
