# Generated by Django 3.1.1 on 2021-03-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_auto_20210328_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='history',
            field=models.IntegerField(),
        ),
    ]
