# Generated by Django 3.0.8 on 2020-10-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_order_is_close'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='order',
            index_together={('order_setting', 'is_close')},
        ),
    ]
