# Generated by Django 3.0.8 on 2020-11-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['time_marker']},
        ),
        migrations.AlterModelOptions(
            name='timemarker',
            options={'ordering': ['time_marker']},
        ),
    ]
